version: '3.7'

services:
  wordpress:
    image: wordpress:6.0.0-php8.0
    ports:
      - "3000:80"
    volumes:
      - "./dist/wp:/var/www/html"
    networks:
      - wp-network
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_db_user
      WORDPRESS_DB_PASSWORD: wp_db_pass
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DEBUG: 1
      
  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - C:\db-docker\.db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_db_user
      MYSQL_PASSWORD: wp_db_pass
      MYSQL_ROOT_PASSWORD: ${MY_SQL_ROOT_PASSWORD}
    networks:
      - wp-network

networks:
  wp-network:

